### ISSUE TITLE
Option to run as normal user, instead of root

### ISSUE THREAD

**Issue by joenepraat** [Krillsson/sys-API#145]
I was always warned not to run applications as root when it's not necessary. This application runs as root, although with some creativity you can run it as a normal user. Wouldn't be possible to give the user out-of-the-box the choice to run sys-APO as a normal user, or even a separated user, or as root like know?

**Comment by Krillsson** [comment]
I agree with you, it's not optimal that you need to run the command line version as root.

Therefore, my recommended way to run this is to use Docker. If you look inside docker-compose.yml, the default has elevated privileges for letting it see the host systems processes, network devices and drives, etc. But I have left the unprivileged version commented out if you like to restrict it.

There's nothing stopping you from running it as your default user over the command line. And if it crashes, that should be fixed. Although you will get empty values where it cannot access the info because of lack of privileges.

Would any of the two alternatives work for you?

**Comment by joenepraat** [comment]
> Would any of the two alternatives work for you?

I'm more of a non-Docker user. 😉 So running it as the default user, would be better. Although I prefer a separate user. Thanks.

**Comment by Krillsson** [comment]
For future reference, I'll leave a quote here from a library contributor of OSHI: https://github.com/oshi/oshi/issues/2426#issuecomment-1666940197

If you can't get this information with your user, from the command line or another app. Then sys-API can't either. I can't work around the security models of Linux.
