### ISSUE TITLE
Not pulling data on mounted hard drives.

### ISSUE THREAD

**Issue by ashkl** [Krillsson/sys-API#64]

**Comment by Krillsson** [comment]
Thanks for opening an issue @ashkl. Could you tell me a bit more about your system?

Platform: linux/macOS/windows?
Version:

And did you get the same result with drives returning 0 from the graphql API? There's info on how to access it in the README.md. And sample queries in the release you downloaded.

**Comment by Krillsson** [comment]
The issue is documented here: https://github.com/oshi/oshi/issues/1578

Essentially, sys-API tries to map physical drives to logical volumes (since they contain the disk usage). And it fails since sometimes there isn't a one to one mapping.
[private fun findAssociatedFileStore(diskStore: HWDiskStore): Optional<OsPartition>](
https://github.com/Krillsson/sys-API/blob/1d55c06c63c1be8439feb6b012b1cf6d6b5760fe/server/src/main/java/com/krillsson/sysapi/core/metrics/defaultimpl/DefaultDriveMetrics.kt#L117)

**Comment by mr-tuduf** [comment]
> The issue is documented here: [oshi/oshi#1578](https://github.com/oshi/oshi/issues/1578)
> 
> Essentially, sys-API tries to map physical drives to logical volumes (since they contain the disk usage). And it fails since sometimes there isn't a one to one mapping. [private fun findAssociatedFileStore(diskStore: HWDiskStore): Optional](https://github.com/Krillsson/sys-API/blob/1d55c06c63c1be8439feb6b012b1cf6d6b5760fe/server/src/main/java/com/krillsson/sysapi/core/metrics/defaultimpl/DefaultDriveMetrics.kt#L117)

no solution to this problem?

**Comment by Krillsson** [comment]
@mr-tuduf I'm working on a solution. Unfortunately I need to abandon the mapping between HWDiskStore and FileSystem. But on the plus-side there will be more information available, since the current code filters out devices and FileSystems it cannot find mapping for.

**Comment by Krillsson** [comment]
after some investigation; it's not OSHI or sys-API. It's when running inside docker. On my system /dev/sda disappears when running inside docker.

**Comment by Krillsson** [comment]
What I've tried so far without success:

```yaml
    privileged: true
    device_cgroup_rules:
      - 'c 8:* rmw'
   volumes:
     - /run/udev:/run/udev:ro
     - /dev:/dev
```

I'm surprised not even privileged option work.
